# Generated by Django 2.2.6 on 2020-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('cp', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=15)),
                ('trestbps', models.IntegerField(default=131)),
                ('chol', models.IntegerField(default=246)),
                ('fbs', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=15)),
                ('restecg', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=15)),
                ('thalach', models.IntegerField(default=149)),
                ('exang', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('oldpeak', models.IntegerField(default=1)),
                ('slope', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=15)),
                ('ca', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15)),
                ('thal', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=15)),
            ],
        ),
    ]
